name = "danaher-ls-xwalk-transformer"
main = "index.js"
compatibility_date = "2022-05-03"
account_id = "852dfa4ae1b0d579df29be65b986c101" #Franklin-Dev
workers_dev = false
routes = [
    { pattern = "danaher-ls-transformer-dev.edge.xwalk.ch", custom_domain = true }
  ]

[vars]
CONTENT_UPSTREAM='https://lifesciences.danaher.com'
BASE_PATH='/'
