name: Deploy Actions

on:
  push:
    paths:
      - .github/workflows/deploy-actions.yaml
      - tools/actions/**
      - tools/importer/import.js
      - paths.yaml
    branches:    
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Danaher
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install -g @adobe/aio-cli
    - name: Run npm ci (convert)
      run: npm ci
      working-directory: tools/actions/convert
    - run: aio app deploy
      working-directory: tools/actions
      env:
        AIO_runtime_auth: ${{ secrets.WSK_AUTH }}
        AIO_runtime_namespace: ${{ secrets.WSK_NAMESPACE }}

      
