name: Linting & Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' #required for npm 8 or later.
    - run: npm ci
    - run: npm ci
      working-directory: tools/actions/convert
    - run: npm run lint
      env:
        CI: true
    - run: npm run test
      working-directory: tools/actions/convert
